/* ================================================================ traducciones: [castellano, inglés, portugués] */
const FRASES = [
  ['SIN BALAS: TIRALA', 'NO AMMO: THROW IT', 'SEM BALAS: JOGA ELA'],
  ['¡PORTAZO!', 'DOOR SLAM!', 'PORTADA!'], ['¡ATADO!', 'TIED UP!', 'AMARRADO!'], ['¡NOCAUT!', 'KNOCKOUT!', 'NOCAUTE!'],
  ['¡REMATE!', 'EXECUTION!', 'EXECUÇÃO!'], ['¡TAJO!', 'SLASH!', 'TALHO!'], ['¡AL VUELO!', 'MID-AIR!', 'NO AR!'], ['PTS', 'PTS', 'PTS'],
  ['¡PISO LIMPIO! VOLVÉ AL AUTO', 'FLOOR CLEAR! BACK TO THE CAR', 'ANDAR LIMPO! VOLTA PRO CARRO'],
  ['¡PISO LIMPIO! SUBÍ', 'FLOOR CLEAR! GO UP', 'ANDAR LIMPO! SOBE'],
  ['¡LA MULITA AGUANTÓ!', 'THE ARMADILLO HELD!', 'O TATU AGUENTOU!'],
  ['{0}× COMBO', '{0}× COMBO', '{0}× COMBO'], ['MANOS', 'FISTS', 'MÃOS'], ['{0} BALAS', '{0} ROUNDS', '{0} BALAS'],
  ['ESTÁS MUERTO', "YOU'RE DEAD", 'VOCÊ MORREU'], ['TOCÁ PARA REINTENTAR', 'TAP TO RETRY', 'TOQUE PARA TENTAR DE NOVO'],
  ['REMATAR', 'EXECUTE', 'EXECUTAR'], ['ATAR', 'TIE UP', 'AMARRAR'], ['AGARRAR', 'PICK UP', 'PEGAR'], ['TIRAR', 'THROW', 'JOGAR'],
  ['SALTEAR', 'SKIP', 'PULAR'], ['RADIO · AM 790', 'RADIO · AM 790', 'RÁDIO · AM 790'],
  ['CONTESTADOR · MENSAJE NUEVO', 'ANSWERING MACHINE · NEW MESSAGE', 'SECRETÁRIA ELETRÔNICA · NOVA MENSAGEM'],
  ['TOCÁ PARA SEGUIR', 'TAP TO CONTINUE', 'TOQUE PARA CONTINUAR'], ['ADVERTENCIA', 'WARNING', 'AVISO'],
  ['ESTE JUEGO TIENE VIOLENCIA GRÁFICA Y SANGRE.', 'THIS GAME HAS GRAPHIC VIOLENCE AND BLOOD.', 'ESTE JOGO TEM VIOLÊNCIA GRÁFICA E SANGUE.'],
  ['EL MODO CENSURA LA CAMBIA POR ESTRELLITAS,', 'CENSORED MODE SWAPS IT FOR LITTLE STARS,', 'O MODO CENSURA TROCA POR ESTRELINHAS,'],
  ['CONFITE Y GOLPES DE DIBUJITO.', 'CONFETTI AND CARTOON BONKS.', 'CONFETE E PANCADAS DE DESENHO.'],
  ['SE PUEDE CAMBIAR CUANDO QUIERAS EN OPCIONES.', 'YOU CAN CHANGE IT ANYTIME IN OPTIONS.', 'DÁ PARA MUDAR QUANDO QUISER NAS OPÇÕES.'],
  ['SIN CENSURA', 'UNCENSORED', 'SEM CENSURA'], ['CON CENSURA', 'CENSORED', 'COM CENSURA'],
  ['BUENOS AIRES · 1989', 'BUENOS AIRES · 1989', 'BUENOS AIRES · 1989'], ['TOCÁ PARA EMPEZAR', 'TAP TO START', 'TOQUE PARA COMEÇAR'],
  ['CAPÍTULOS', 'CHAPTERS', 'CAPÍTULOS'], ['SEGUIR', 'CONTINUE', 'CONTINUAR'], ['JUGAR', 'PLAY', 'JOGAR'], ['MÁSCARAS', 'MASKS', 'MÁSCARAS'],
  ['OPCIONES', 'OPTIONS', 'OPÇÕES'], ['MODO CENSURA', 'CENSORED MODE', 'MODO CENSURA'], ['VOLVER', 'BACK', 'VOLTAR'],
  ['ELEGÍ TU MÁSCARA', 'PICK YOUR MASK', 'ESCOLHA SUA MÁSCARA'], ['¡VAMOS!', "LET'S GO!", 'VAMOS!'], ['SÍ', 'YES', 'SIM'], ['NO', 'NO', 'NÃO'],
  ['IDIOMA', 'LANGUAGE', 'IDIOMA'], ['MÚSICA', 'MUSIC', 'MÚSICA'], ['EFECTOS', 'SOUND FX', 'EFEITOS'],
  ['BALANCEO DE CÁMARA', 'CAMERA SWAY', 'BALANÇO DA CÂMERA'], ['EFECTOS VISUALES', 'VISUAL EFFECTS', 'EFEITOS VISUAIS'],
  ['ALTOS', 'HIGH', 'ALTOS'], ['BAJOS', 'LOW', 'BAIXOS'], ['VIBRACIÓN', 'VIBRATION', 'VIBRAÇÃO'], ['PAUSA', 'PAUSE', 'PAUSA'],
  ['REINTENTAR PISO', 'RETRY FLOOR', 'REPETIR ANDAR'], ['SALIR AL MENÚ', 'QUIT TO MENU', 'SAIR PARA O MENU'],
  ['TOTAL', 'TOTAL', 'TOTAL'], ['NOTA', 'GRADE', 'NOTA'], ['¡RÉCORD!', 'NEW RECORD!', 'RECORDE!'], ['CONTINUAR', 'CONTINUE', 'CONTINUAR'],
  ['BAJAS', 'KILLS', 'ABATES'], ['COMBO MÁXIMO', 'MAX COMBO', 'COMBO MÁXIMO'], ['ARMAS DISTINTAS', 'WEAPONS USED', 'ARMAS DIFERENTES'], ['TIEMPO', 'TIME', 'TEMPO'],
  ['PALANCA IZQUIERDA: CAMINÁ', 'LEFT STICK: WALK', 'ALAVANCA ESQUERDA: ANDE'],
  ['DERECHA: APUNTÁ. HASTA EL FONDO: PIÑA', 'RIGHT: AIM. ALL THE WAY: PUNCH', 'DIREITA: MIRE. ATÉ O FIM: SOCO'],
  ['LA PIÑA VOLTEA. ¡REMATALO CON EL BOTÓN!', 'PUNCHES KNOCK DOWN. EXECUTE WITH THE BUTTON!', 'O SOCO DERRUBA. EXECUTE COM O BOTÃO!'],
  ['AGARRÁ UN ARMA DEL PISO CON EL BOTÓN', 'PICK UP A WEAPON WITH THE BUTTON', 'PEGUE UMA ARMA DO CHÃO COM O BOTÃO'],
  ['ABRÍ LAS PUERTAS DE GOLPE: VOLTEAN', 'SLAM DOORS OPEN: THEY KNOCK DOWN', 'ABRA AS PORTAS COM TUDO: ELAS DERRUBAM'],
  ['LIMPIÁ LA CASA Y VOLVÉ AL AUTO', 'CLEAR THE HOUSE AND GET BACK TO THE CAR', 'LIMPE A CASA E VOLTE PRO CARRO'],
  ['BUENOS AIRES, MARZO DE 1989.', 'BUENOS AIRES, MARCH 1989.', 'BUENOS AIRES, MARÇO DE 1989.'],
  ['LA INFLACIÓN VA POR EL 17% POR MES.', 'INFLATION IS RUNNING AT 17% A MONTH.', 'A INFLAÇÃO ESTÁ EM 17% AO MÊS.'],
  ['Hola, querido, habla Norma, de la panadería La Espiga.', "Hi, sweetie, it's Norma, from La Espiga bakery.", 'Oi, querido, aqui é a Norma, da padaria La Espiga.'],
  ['Te dejé un pedido de prueba en la calle Bacacay, en Floresta. Una casita, una pavada.', 'I left you a trial order on Bacacay street, in Floresta. A little house, easy stuff.', 'Deixei um pedido de teste na rua Bacacay, em Floresta. Uma casinha, moleza.'],
  ['La máscara está en la puerta. Y no le cuentes a nadie. Besito.', "The mask is at your door. And don't tell anyone. Kisses.", 'A máscara está na porta. E não conte pra ninguém. Beijinho.'],
  ['Hola, habla Norma otra vez. Hay un pedido grande de facturas en Lavalle al 2200, en Once.', "Hi, it's Norma again. There's a big pastry order at 2200 Lavalle, in Once.", 'Oi, é a Norma de novo. Tem um pedido grande de doces na Lavalle 2200, em Once.'],
  ['Dos pisos. Los muchachos de traje blanco no pagaron la cuenta. Ya sabés cómo se cobra.', "Two floors. The boys in white suits didn't pay their bill. You know how to collect.", 'Dois andares. Os rapazes de terno branco não pagaram a conta. Você sabe como se cobra.'],
  ['Querido, ¿me escuchás? Esta noche hay baile en el Tropical de Constitución.', "Sweetie, can you hear me? There's a dance tonight at the Tropical, in Constitución.", 'Querido, está me ouvindo? Hoje à noite tem baile no Tropical, em Constitución.'],
  ['Cumbia hasta las seis. Los de traje blanco festejan algo. Arruinales la fiesta.', "Cumbia till six. The white suits are celebrating something. Ruin their party.", 'Cumbia até as seis. Os de terno branco estão comemorando algo. Estrague a festa.'],
  ['...y el dólar cerró hoy a doscientos australes. Los supermercados remarcan dos veces por día...', '...and the dollar closed today at two hundred australes. Supermarkets reprice twice a day...', '...e o dólar fechou hoje a duzentos austrais. Os supermercados remarcam duas vezes por dia...'],
  ['Hay un envío en un depósito de Dock Sud. Contenedores, perros y guardias con fusiles.', "There's a shipment in a warehouse in Dock Sud. Containers, dogs and guards with rifles.", 'Tem uma remessa num depósito em Dock Sud. Contêineres, cães e guardas com fuzis.'],
  ['Los dólares salen de ahí. Que no salga nada más.', 'The dollars come out of there. Make sure nothing else does.', 'Os dólares saem de lá. Que não saia mais nada.'],
  ['Así que vos sos el de la máscara.', "So you're the one with the mask.", 'Então você é o da máscara.'],
  ['Norma no existe, pibe. Nunca existió. Vení a San Isidro y te cuento quién te llama.', "Norma doesn't exist, kid. She never did. Come to San Isidro and I'll tell you who's calling.", 'A Norma não existe, garoto. Nunca existiu. Venha a San Isidro que eu conto quem te liga.'],
  ['Te espero en el sótano.', "I'll be waiting in the basement.", 'Te espero no porão.'],
  ['EL PATRÓN CAYÓ. LA PATOTA SE DESBANDÓ.', 'THE BOSS FELL. THE GANG SCATTERED.', 'O PATRÃO CAIU. A GANGUE SE DISPERSOU.'],
  ['EL DÓLAR SIGUIÓ SUBIENDO.', 'THE DOLLAR KEPT RISING.', 'O DÓLAR CONTINUOU SUBINDO.'],
  ['Hola, querido. Habla Norma. Tengo otro pedido.', "Hi, sweetie. It's Norma. I have another order.", 'Oi, querido. Aqui é a Norma. Tenho outro pedido.'],
  ['¿QUIÉN LLAMA?', "WHO'S CALLING?", 'QUEM ESTÁ LIGANDO?'],
  ['PRÓLOGO', 'PROLOGUE', 'PRÓLOGO'], ['LA PRUEBA', 'THE TRIAL', 'O TESTE'], ['3 DE MARZO DE 1989', 'MARCH 3, 1989', '3 DE MARÇO DE 1989'], ['FLORESTA', 'FLORESTA', 'FLORESTA'],
  ['CAPÍTULO 1', 'CHAPTER 1', 'CAPÍTULO 1'], ['TARIFA SOCIAL', 'SOCIAL RATE', 'TARIFA SOCIAL'], ['14 DE ABRIL DE 1989', 'APRIL 14, 1989', '14 DE ABRIL DE 1989'], ['ONCE', 'ONCE', 'ONCE'],
  ['CAPÍTULO 2', 'CHAPTER 2', 'CAPÍTULO 2'], ['NOCHE DE CUMBIA', 'CUMBIA NIGHT', 'NOITE DE CUMBIA'], ['20 DE MAYO DE 1989', 'MAY 20, 1989', '20 DE MAIO DE 1989'], ['CONSTITUCIÓN', 'CONSTITUCIÓN', 'CONSTITUCIÓN'],
  ['CAPÍTULO 3', 'CHAPTER 3', 'CAPÍTULO 3'], ['LA HIPER', 'HYPERINFLATION', 'A HIPER'], ['29 DE MAYO DE 1989', 'MAY 29, 1989', '29 DE MAIO DE 1989'], ['DOCK SUD', 'DOCK SUD', 'DOCK SUD'],
  ['CAPÍTULO 4', 'CHAPTER 4', 'CAPÍTULO 4'], ['EL PATRÓN', 'THE BOSS', 'O PATRÃO'], ['9 DE JULIO DE 1989', 'JULY 9, 1989', '9 DE JULHO DE 1989'], ['SAN ISIDRO', 'SAN ISIDRO', 'SAN ISIDRO'],
  ['BATE', 'BAT', 'TACO'], ['CAÑO', 'PIPE', 'CANO'], ['CUCHILLO', 'KNIFE', 'FACA'], ['KATANA', 'KATANA', 'KATANA'], ['PISTOLA', 'PISTOL', 'PISTOLA'],
  ['SILENCIADA', 'SILENCED', 'SILENCIADA'], ['UZI', 'UZI', 'UZI'], ['ESCOPETA', 'SHOTGUN', 'ESPINGARDA'], ['FUSIL', 'RIFLE', 'FUZIL'],
  ['CARPINCHO', 'CAPYBARA', 'CAPIVARA'], ['EL DE SIEMPRE. SIN VENTAJAS', 'THE CLASSIC. NO PERKS', 'O DE SEMPRE. SEM VANTAGENS'],
  ['CÓNDOR', 'CONDOR', 'CONDOR'], ['CORRÉS MÁS RÁPIDO', 'YOU RUN FASTER', 'VOCÊ CORRE MAIS RÁPIDO'],
  ['YAGUARETÉ', 'JAGUAR', 'ONÇA'], ['LAS PIÑAS MATAN', 'PUNCHES KILL', 'OS SOCOS MATAM'],
  ['HORNERO', 'OVENBIRD', 'JOÃO-DE-BARRO'], ['LOS PORTAZOS MATAN', 'DOOR SLAMS KILL', 'AS PORTADAS MATAM'],
  ['MULITA', 'ARMADILLO', 'TATU'], ['AGUANTÁS UN TIRO', 'YOU TAKE ONE BULLET', 'VOCÊ AGUENTA UM TIRO'],
  ['VIZCACHA', 'VISCACHA', 'VISCACHA'], ['MÁS BALAS EN CADA ARMA', 'MORE AMMO IN EVERY GUN', 'MAIS BALAS EM CADA ARMA'],
  ['LÍNEA CALIENTE', 'LÍNEA CALIENTE', 'LÍNEA CALIENTE'], ['UNA BETA HECHA EN PÍXELES', 'A BETA MADE OF PIXELS', 'UMA BETA FEITA DE PIXELS'],
  ['DIBUJO, CÓDIGO Y MÚSICA POR CÓDIGO', 'ART, CODE AND MUSIC, ALL CODE', 'ARTE, CÓDIGO E MÚSICA, TUDO CÓDIGO'],
  ['HOMENAJE A HOTLINE MIAMI', 'A TRIBUTE TO HOTLINE MIAMI', 'HOMENAGEM A HOTLINE MIAMI'], ['GRACIAS POR JUGAR', 'THANKS FOR PLAYING', 'OBRIGADO POR JOGAR'],
  ['NORMA', 'NORMA', 'NORMA'], ['RADIO', 'RADIO', 'RÁDIO'], ['ESPAÑOL', 'ESPAÑOL', 'ESPAÑOL'], ['ENGLISH', 'ENGLISH', 'ENGLISH'], ['PORTUGUÊS', 'PORTUGUÊS', 'PORTUGUÊS']
];
