/* ================================================================ las frases: [castellano (la clave), inglés, portugués] */
const FRASES = [
['NO LO DEJES ENTRAR', "DON'T LET IT IN", 'NÃO DEIXE ELE ENTRAR'],
['NO LO DEJES', "DON'T LET", 'NÃO DEIXE'],
['ENTRAR', 'IT IN', 'ELE ENTRAR'],
['Una noche. Una casa. Algo afuera.', 'One night. One house. Something outside.', 'Uma noite. Uma casa. Algo lá fora.'],
['Noches sobrevividas: {0}', 'Nights survived: {0}', 'Noites sobrevividas: {0}'],
['JUGAR', 'PLAY', 'JOGAR'],
['CÓMO SE JUEGA', 'HOW TO PLAY', 'COMO JOGAR'],
['OPCIONES', 'OPTIONS', 'OPÇÕES'],
['IDIOMA', 'LANGUAGE', 'IDIOMA'],
['Con auriculares da más miedo.', "It's scarier with headphones.", 'Com fones de ouvido dá mais medo.'],
['DIFICULTAD', 'DIFFICULTY', 'DIFICULDADE'],
['FÁCIL', 'EASY', 'FÁCIL'],
['Más tablas, más tiempo, el bicho tarda más.', 'More planks, more time, the creature is slower.', 'Mais tábuas, mais tempo, a criatura demora mais.'],
['NORMAL', 'NORMAL', 'NORMAL'],
['Como en el original.', 'Like the original.', 'Como no original.'],
['PESADILLA', 'NIGHTMARE', 'PESADELO'],
['Menos tablas, más hambre, sin reintentos.', 'Fewer planks, more hunger, no retries.', 'Menos tábuas, mais fome, sem novas tentativas.'],
['VOLVER', 'BACK', 'VOLTAR'],
['TRANSMISIÓN DE EMERGENCIA', 'EMERGENCY BROADCAST', 'TRANSMISSÃO DE EMERGÊNCIA'],
['PREPARATE (hasta las 12): buscá la linterna, agarrá las tablas de arriba y clavalas en las ventanas, instalá las cámaras de afuera y llená el generador en el galpón del fondo.',
 'PREPARE (until 12): find the flashlight, grab the planks upstairs and nail them over the windows, install the outdoor cameras and fill the generator in the back shed.',
 'PREPARE-SE (até a meia-noite): ache a lanterna, pegue as tábuas lá em cima e pregue nas janelas, instale as câmeras de fora e encha o gerador no galpão dos fundos.'],
['SOBREVIVÍ (de 12 a 6): cuando escuches que respira del otro lado de una ventana, corré a ese cuarto y prendé la luz. No prendas todas a la vez: saltan los fusibles.',
 'SURVIVE (12 to 6): when you hear it breathing on the other side of a window, run to that room and turn on the light. Don\'t turn them all on at once: the fuses will blow.',
 'SOBREVIVA (da meia-noite às 6): quando ouvir a respiração do outro lado de uma janela, corra para esse quarto e acenda a luz. Não acenda todas de uma vez: os fusíveis queimam.'],
['Si entra, escondete en un placard y aguantá la puerta con ◀ ▶. El generador te da aire: si se apaga, te asfixiás.',
 'If it gets in, hide in a closet and hold the door with ◀ ▶. The generator gives you air: if it stops, you suffocate.',
 'Se ele entrar, esconda-se num armário e segure a porta com ◀ ▶. O gerador te dá ar: se ele parar, você sufoca.'],
['Izquierda: caminar. Derecha: mirar. La mano sirve para todo; mantenela apretada para clavar o cargar nafta.',
 'Left: walk. Right: look. The hand does everything; hold it down to hammer or pour fuel.',
 'Esquerda: andar. Direita: olhar. A mão serve para tudo; segure para pregar ou pôr gasolina.'],
['CALIDAD', 'QUALITY', 'QUALIDADE'],
['BAJA', 'LOW', 'BAIXA'],
['MEDIA', 'MEDIUM', 'MÉDIA'],
['ALTA', 'HIGH', 'ALTA'],
['SENSIBILIDAD', 'SENSITIVITY', 'SENSIBILIDADE'],
['BRILLO', 'BRIGHTNESS', 'BRILHO'],
['MÚSICA', 'MUSIC', 'MÚSICA'],
['NO', 'NO', 'NÃO'],
['SÍ', 'YES', 'SIM'],
['SONIDO', 'SOUND', 'SOM'],
['SUBTÍTULOS', 'SUBTITLES', 'LEGENDAS'],
['VIBRACIÓN', 'VIBRATION', 'VIBRAÇÃO'],
['PAUSA', 'PAUSED', 'PAUSA'],
['SEGUIR', 'RESUME', 'CONTINUAR'],
['SALIR AL MENÚ', 'QUIT TO MENU', 'SAIR PARA O MENU'],
['MORISTE', 'YOU DIED', 'VOCÊ MORREU'],
['Consejo:', 'Tip:', 'Dica:'],
['REINTENTAR DESDE LAS 12', 'RETRY FROM 12 AM', 'TENTAR DE NOVO DA MEIA-NOITE'],
['EMPEZAR DE NUEVO', 'START OVER', 'COMEÇAR DE NOVO'],
['MENÚ', 'MENU', 'MENU'],
['SOBREVIVISTE', 'YOU SURVIVED', 'VOCÊ SOBREVIVEU'],
['Llegaste a las 6 AM.', 'You made it to 6 AM.', 'Você chegou às 6 AM.'],
['Tablas clavadas: {0}', 'Planks nailed: {0}', 'Tábuas pregadas: {0}'],
['Veces que lo echaste: {0}', 'Times you scared it off: {0}', 'Vezes que você o espantou: {0}'],
['Nafta cargada: {0}%', 'Fuel poured: {0}%', 'Gasolina colocada: {0}%'],
['Veces que aguantaste en el placard: {0}', 'Times you held the closet: {0}', 'Vezes que você aguentou no armário: {0}'],
['JUGAR OTRA VEZ', 'PLAY AGAIN', 'JOGAR DE NOVO'],
['TE ENCONTRÓ', 'IT FOUND YOU', 'ELE TE ACHOU'],
['TE AGARRÓ AFUERA', 'IT CAUGHT YOU OUTSIDE', 'ELE TE PEGOU LÁ FORA'],
['TE QUEDASTE SIN AIRE', 'YOU RAN OUT OF AIR', 'VOCÊ FICOU SEM AR'],
['TE PISÓ UN PATRULLERO', 'A POLICE CAR RAN YOU OVER', 'UMA VIATURA TE ATROPELOU'],
['TE SACÓ DEL PLACARD', 'IT PULLED YOU OUT OF THE CLOSET', 'ELE TE TIROU DO ARMÁRIO'],
['Si entra, escondete en un placard y aguantá la puerta en el centro.', 'If it gets in, hide in a closet and keep the door at the center.', 'Se ele entrar, esconda-se num armário e segure a porta no centro.'],
['Afuera es peligroso. Salí justo después de echarlo de una ventana.', 'Outside is dangerous. Go out right after you scare it off a window.', 'Lá fora é perigoso. Saia logo depois de espantá-lo de uma janela.'],
['No dejes que el generador se quede sin nafta: sin él no hay aire.', "Don't let the generator run out of fuel: without it there's no air.", 'Não deixe o gerador ficar sem gasolina: sem ele não há ar.'],
['A las 9 pasan los patrulleros. No te quedes en la calle.', "At 9 the police cars come by. Don't stay in the street.", 'Às 9 passam as viaturas. Não fique na rua.'],
['Usá las luces de la casa para asustarlo de las ventanas.', 'Use the house lights to scare it away from the windows.', 'Use as luzes da casa para espantá-lo das janelas.'],
['Cuando tire de la puerta, tocá ◀ ▶ para que la marca no salga del centro.', 'When it pulls the door, tap ◀ ▶ to keep the marker in the center.', 'Quando ele puxar a porta, toque ◀ ▶ para manter a marca no centro.'],
['Buscá la linterna', 'Find the flashlight', 'Ache a lanterna'],
['Tapá una ventana con tablas', 'Board up a window', 'Tape uma janela com tábuas'],
['Instalá una cámara', 'Install a camera', 'Instale uma câmera'],
['Cargá el generador', 'Refuel the generator', 'Abasteça o gerador'],
['Objetivo:', 'Objective:', 'Objetivo:'],
['Entrá a tu casa', 'Go inside your house', 'Entre na sua casa'],
['Escuchá la radio', 'Listen to the radio', 'Ouça o rádio'],
['La radio del living está haciendo ruido...', 'The living room radio is making noise...', 'O rádio da sala está chiando...'],
['Preparate para la noche', 'Prepare for the night', 'Prepare-se para a noite'],
['Sobreviví la noche', 'Survive the night', 'Sobreviva à noite'],
['12 AM', '12 AM', '12 AM'],
['6 AM', '6 AM', '6 AM'],
['PRENDER LA RADIO', 'TURN ON THE RADIO', 'LIGAR O RÁDIO'],
['ESCUCHAR LA RADIO', 'LISTEN TO THE RADIO', 'OUVIR O RÁDIO'],
['ADELANTAR LA NOCHE', 'SKIP TO NIGHT', 'ADIANTAR A NOITE'],
['Mejor que esté todo listo...', 'Better have everything ready...', 'Melhor estar tudo pronto...'],
['APAGAR LA TELE', 'TURN OFF THE TV', 'DESLIGAR A TV'],
['PRENDER LA TELE', 'TURN ON THE TV', 'LIGAR A TV'],
['No hay luz.', "There's no power.", 'Não tem luz.'],
['ATENDER', 'ANSWER', 'ATENDER'],
['TELÉFONO', 'PHONE', 'TELEFONE'],
['CAJÓN VACÍO', 'EMPTY DRAWER', 'GAVETA VAZIA'],
['BUSCAR EN EL CAJÓN', 'SEARCH THE DRAWER', 'PROCURAR NA GAVETA'],
['AGARRAR PILAS', 'TAKE BATTERIES', 'PEGAR PILHAS'],
['Una linterna. Con esto me arreglo.', 'A flashlight. This will do.', 'Uma lanterna. Com isso eu me viro.'],
['NO HAY NADA', "THERE'S NOTHING", 'NÃO TEM NADA'],
['Pilas. Me van a hacer falta.', "Batteries. I'm going to need them.", 'Pilhas. Vou precisar delas.'],
['ABRIR LA HELADERA', 'OPEN THE FRIDGE', 'ABRIR A GELADEIRA'],
['HELADERA VACÍA', 'EMPTY FRIDGE', 'GELADEIRA VAZIA'],
['Gaseosas. Para correr.', 'Sodas. For running.', 'Refrigerantes. Para correr.'],
['AGARRAR LA LLAVE INGLESA', 'TAKE THE WRENCH', 'PEGAR A CHAVE INGLESA'],
['Para la caja de fusibles.', 'For the fuse box.', 'Para a caixa de fusíveis.'],
['AGARRAR TABLAS ({0})', 'TAKE PLANKS ({0})', 'PEGAR TÁBUAS ({0})'],
['NO QUEDAN TABLAS', 'NO PLANKS LEFT', 'NÃO SOBROU TÁBUA'],
['No puedo llevar más de tres.', "I can't carry more than three.", 'Não consigo levar mais de três.'],
['No quedan tablas.', 'No planks left.', 'Não sobrou tábua.'],
['TIENE 3 TABLAS', 'HAS 3 PLANKS', 'TEM 3 TÁBUAS'],
['CLAVAR UNA TABLA ({0}/3)', 'NAIL A PLANK ({0}/3)', 'PREGAR UMA TÁBUA ({0}/3)'],
['NECESITÁS TABLAS ({0}/3)', 'YOU NEED PLANKS ({0}/3)', 'VOCÊ PRECISA DE TÁBUAS ({0}/3)'],
['Las tablas están arriba, en el dormitorio.', 'The planks are upstairs, in the bedroom.', 'As tábuas estão lá em cima, no quarto.'],
['NO HAY LUZ', 'NO POWER', 'SEM LUZ'],
['APAGAR LA LUZ', 'TURN OFF THE LIGHT', 'APAGAR A LUZ'],
['PRENDER LA LUZ', 'TURN ON THE LIGHT', 'ACENDER A LUZ'],
['Saltaron los fusibles. La caja está atrás de la casa.', 'The fuses blew. The box is behind the house.', 'Os fusíveis queimaram. A caixa fica atrás da casa.'],
['ROTA', 'BROKEN', 'QUEBRADA'],
['CERRAR', 'CLOSE', 'FECHAR'],
['SACAR LA LLAVE', 'UNLOCK', 'DESTRANCAR'],
['ABRIR', 'OPEN', 'ABRIR'],
['CERRÁ LA PUERTA PRIMERO', 'CLOSE THE DOOR FIRST', 'FECHE A PORTA PRIMEIRO'],
['CERRAR CON LLAVE', 'LOCK', 'TRANCAR'],
['ESCONDERSE', 'HIDE', 'ESCONDER-SE'],
['VER LAS CÁMARAS', 'VIEW CAMERAS', 'VER AS CÂMERAS'],
['Sin luz no anda la compu.', "The computer doesn't work without power.", 'Sem luz o computador não funciona.'],
['INSTALAR {0}', 'INSTALL {0}', 'INSTALAR {0}'],
['Listo. Se ve desde la compu de arriba.', 'Done. You can see it from the computer upstairs.', 'Pronto. Dá para ver no computador lá de cima.'],
['CARGAR NAFTA ({0}/100)', 'POUR FUEL ({0}/100)', 'COLOCAR GASOLINA ({0}/100)'],
['GENERADOR {0}/100', 'GENERATOR {0}/100', 'GERADOR {0}/100'],
['El bidón está vacío. El tambor está al lado.', 'The gas can is empty. The drum is next to it.', 'O galão está vazio. O tambor está do lado.'],
['Necesito el bidón de nafta.', 'I need the gas can.', 'Preciso do galão de gasolina.'],
['Está lleno.', "It's full.", 'Está cheio.'],
['TAMBOR DE NAFTA', 'FUEL DRUM', 'TAMBOR DE GASOLINA'],
['EL BIDÓN ESTÁ LLENO', 'THE GAS CAN IS FULL', 'O GALÃO ESTÁ CHEIO'],
['LLENAR EL BIDÓN', 'FILL THE GAS CAN', 'ENCHER O GALÃO'],
['Me falta el bidón.', "I don't have the gas can.", 'Falta o galão.'],
['AGARRAR EL BIDÓN', 'TAKE THE GAS CAN', 'PEGAR O GALÃO'],
['Lleno. El generador está acá al lado.', 'Full. The generator is right here.', 'Cheio. O gerador está aqui do lado.'],
['LOS FUSIBLES ANDAN', 'THE FUSES ARE FINE', 'OS FUSÍVEIS ESTÃO BONS'],
['ARREGLAR LOS FUSIBLES', 'FIX THE FUSES', 'CONSERTAR OS FUSÍVEIS'],
['NECESITÁS LA LLAVE INGLESA', 'YOU NEED THE WRENCH', 'VOCÊ PRECISA DA CHAVE INGLESA'],
['Necesito la llave inglesa. Creo que está en el lavadero.', 'I need the wrench. I think it\'s in the laundry room.', 'Preciso da chave inglesa. Acho que está na lavanderia.'],
['Se apagó el generador... no hay aire.', 'The generator died... there\'s no air.', 'O gerador apagou... não tem ar.'],
['No instalé ninguna cámara todavía.', "I haven't installed any cameras yet.", 'Ainda não instalei nenhuma câmera.'],
['ÚLTIMO MOMENTO', 'BREAKING NEWS', 'URGENTE'],
['DERRAME EN PLANTA BLOXIA', 'SPILL AT BLOXIA PLANT', 'VAZAMENTO NA FÁBRICA BLOXIA'],
['Por fin en casa. ¿Qué es ese olor?', "Home at last. What's that smell?", 'Enfim em casa. Que cheiro é esse?'],
['¿Un derrame? ¿Acá al lado?', 'A spill? Right next door?', 'Um vazamento? Aqui do lado?'],
['No llegué a prepararme... ya es tarde.', "I didn't get ready in time... it's too late.", 'Não deu tempo de me preparar... já é tarde.'],
['¿Quién golpea a esta hora?', "Who's knocking at this hour?", 'Quem está batendo a essa hora?'],
['Volvió la luz.', 'The power is back.', 'A luz voltou.'],
['...SALE EL SOL. SE TERMINÓ. SI ESTÁN ESCUCHANDO ESTO, SOBREVIVIERON.', "...THE SUN IS RISING. IT'S OVER. IF YOU CAN HEAR THIS, YOU SURVIVED.", '...O SOL ESTÁ NASCENDO. ACABOU. SE VOCÊS ESTÃO OUVINDO ISSO, SOBREVIVERAM.'],
['No tengo linterna.', "I don't have a flashlight.", 'Não tenho lanterna.'],
['No me quedan pilas.', "I'm out of batteries.", 'Não tenho mais pilhas.'],
['El bidón está en el galpón, atrás.', 'The gas can is in the shed, out back.', 'O galão está no galpão, nos fundos.'],
['Se quedó sin pilas.', 'The batteries died.', 'A pilha acabou.'],
['RADIO', 'RADIO', 'RÁDIO'],
['SALIR', 'EXIT', 'SAIR'],
['Aguantá la puerta: mantené la marca en el centro', 'Hold the door: keep the marker in the center', 'Segure a porta: mantenha a marca no centro'],
['CAJA DE FUSIBLES', 'FUSE BOX', 'CAIXA DE FUSÍVEIS'],
['Tocá con la llave el cable que echa chispas.', 'Touch the sparking wire with the wrench.', 'Toque com a chave o fio que solta faíscas.'],
['LLENO', 'FULL', 'CHEIO'],
['VACÍO', 'EMPTY', 'VAZIO'],
['SEÑAL PERDIDA', 'SIGNAL LOST', 'SINAL PERDIDO'],
['CÁMARA 1', 'CAMERA 1', 'CÂMERA 1'],
['CÁMARA 2', 'CAMERA 2', 'CÂMERA 2'],
['CÁMARA 3', 'CAMERA 3', 'CÂMERA 3'],
['ATENCIÓN, VECINOS DEL BARRIO BLOXIA. ESTO ES UN AVISO DE EMERGENCIA.', 'ATTENTION, RESIDENTS OF BLOXIA. THIS IS AN EMERGENCY ALERT.', 'ATENÇÃO, MORADORES DO BAIRRO BLOXIA. ESTE É UM AVISO DE EMERGÊNCIA.'],
['ESTA TARDE HUBO UN DERRAME QUÍMICO EN LA PLANTA. NO SABEMOS QUÉ SALIÓ DE AHÍ.', "THIS AFTERNOON THERE WAS A CHEMICAL SPILL AT THE PLANT. WE DON'T KNOW WHAT CAME OUT OF IT.", 'HOJE À TARDE HOUVE UM VAZAMENTO QUÍMICO NA FÁBRICA. NÃO SABEMOS O QUE SAIU DE LÁ.'],
['ANTES DE LAS DOCE, TAPEN LAS VENTANAS CON TABLAS. INSTALEN LAS CÁMARAS DE AFUERA.', 'BEFORE MIDNIGHT, BOARD UP YOUR WINDOWS. INSTALL THE OUTDOOR CAMERAS.', 'ANTES DA MEIA-NOITE, TAPEM AS JANELAS COM TÁBUAS. INSTALEM AS CÂMERAS DE FORA.'],
['MANTENGAN EL GENERADOR CARGADO: SIN ÉL, EL AIRE DE LA CASA SE VUELVE IRRESPIRABLE.', 'KEEP THE GENERATOR FUELED: WITHOUT IT, THE AIR IN THE HOUSE BECOMES UNBREATHABLE.', 'MANTENHAM O GERADOR ABASTECIDO: SEM ELE, O AR DA CASA FICA IRRESPIRÁVEL.'],
['SI ALGO QUIERE ENTRAR, PRENDAN LA LUZ DE ESE CUARTO. NO LE GUSTA LA LUZ.', "IF SOMETHING TRIES TO GET IN, TURN ON THE LIGHT IN THAT ROOM. IT DOESN'T LIKE THE LIGHT.", 'SE ALGO QUISER ENTRAR, ACENDAM A LUZ DESSE CÔMODO. ELE NÃO GOSTA DE LUZ.'],
['Y SI ENTRA... ESCÓNDANSE. NO LO DEJEN ENTRAR.', "AND IF IT GETS IN... HIDE. DON'T LET IT IN.", 'E SE ELE ENTRAR... ESCONDAM-SE. NÃO DEIXEM ELE ENTRAR.'],
['ÚLTIMO AVISO: TOQUE DE QUEDA. QUE NADIE SALGA A LA CALLE.', 'FINAL WARNING: CURFEW. NOBODY GOES OUTSIDE.', 'ÚLTIMO AVISO: TOQUE DE RECOLHER. NINGUÉM SAI NA RUA.'],
['...REPETIMOS: NO SALGAN. NO ABRAN LA PUERTA, AUNQUE ESCUCHEN UNA VOZ CONOCIDA...', "...WE REPEAT: DON'T GO OUT. DON'T OPEN THE DOOR, EVEN IF YOU HEAR A FAMILIAR VOICE...", '...REPETIMOS: NÃO SAIAM. NÃO ABRAM A PORTA, MESMO QUE OUÇAM UMA VOZ CONHECIDA...'],
['...SE REPORTAN CORTES DE LUZ EN TODO EL BARRIO...', '...POWER OUTAGES REPORTED ACROSS THE NEIGHBORHOOD...', '...HÁ RELATOS DE FALTA DE LUZ EM TODO O BAIRRO...'],
['...FALTA POCO PARA EL AMANECER. LOS EQUIPOS LLEGAN CON EL SOL. AGUANTEN...', '...DAWN IS CLOSE. THE TEAMS ARRIVE WITH THE SUN. HOLD ON...', '...FALTA POUCO PARA O AMANHECER. AS EQUIPES CHEGAM COM O SOL. AGUENTEM...'],
['¿HOLA? ...', 'HELLO? ...', 'ALÔ? ...'],
['(RESPIRA)', '(BREATHING)', '(RESPIRAÇÃO)'],
['...TE VI ENTRAR.', '...I SAW YOU GO IN.', '...EU VI VOCÊ ENTRAR.'],
['...ABRIME LA VENTANA...', '...OPEN THE WINDOW FOR ME...', '...ABRE A JANELA PRA MIM...']
];
