/* ================================================================ idiomas: [castellano, inglés, portugués]
   La frase en castellano es la clave; {0} es un número o un nombre. Lo que falte queda en TR_FALTA. */
const FRASES = [
  ['EL ÚLTIMO RŌNIN', 'THE LAST RŌNIN', 'O ÚLTIMO RŌNIN'],
  ['EL ÚLTIMO', 'THE LAST', 'O ÚLTIMO'],
  ['RŌNIN', 'RŌNIN', 'RŌNIN'],
  ['Desviá. Esperá. Cortá.', 'Parry. Wait. Strike.', 'Desvie. Espere. Corte.'],
  ['élite', 'elite', 'elite'],
  ['ryo', 'ryo', 'ryo'],
  /* luchadores */
  ['Bandido de la montaña', 'Mountain Bandit', 'Bandido da montanha'],
  ['Lancero ashigaru', 'Ashigaru Spearman', 'Lanceiro ashigaru'],
  ['Shinobi', 'Shinobi', 'Shinobi'],
  ['Monje guerrero', 'Warrior Monk', 'Monge guerreiro'],
  ['General Akagane', 'General Akagane', 'General Akagane'],
  ['Kageyama, el maestro de la espada', 'Kageyama, the Sword Master', 'Kageyama, o mestre da espada'],
  ['Shuten, el oni', 'Shuten, the Oni', 'Shuten, o oni'],
  ['Gashadokuro', 'Gashadokuro', 'Gashadokuro'],
  ['Oogama', 'Oogama', 'Oogama'],
  /* espadas y rangos */
  ['Katana sin nombre', 'Nameless Katana', 'Katana sem nome'],
  ['Filo del viento', 'Wind Edge', 'Fio do vento'],
  ['Espada de Shura', 'Blade of Shura', 'Espada de Shura'],
  ['Luna creciente', 'Crescent Moon', 'Lua crescente'],
  ['Muramasa maldita', 'Cursed Muramasa', 'Muramasa amaldiçoada'],
  ['Común', 'Common', 'Comum'],
  ['Rara', 'Rare', 'Rara'],
  ['Épica', 'Epic', 'Épica'],
  ['Legendaria', 'Legendary', 'Lendária'],
  ['Mítica', 'Mythic', 'Mítica'],
  /* habilidades */
  ['Aniquilación', 'Annihilation', 'Aniquilação'],
  ['Un torbellino de cuatro tajos imparables.', 'A whirlwind of four unstoppable slashes.', 'Um redemoinho de quatro cortes imparáveis.'],
  ['Concentración', 'Concentration', 'Concentração'],
  ['CONCENTRACIÓN', 'CONCENTRATION', 'CONCENTRAÇÃO'],
  ['Tus próximos cinco ataques son contragolpes relámpago.', 'Your next five attacks are lightning counters.', 'Seus próximos cinco ataques são contragolpes relâmpago.'],
  ['Distorsión del tiempo', 'Time Distortion', 'Distorção do tempo'],
  ['El enemigo se mueve a un tercio de su velocidad durante 6 segundos.', 'The enemy moves at a third of its speed for 6 seconds.', 'O inimigo se move a um terço da velocidade por 6 segundos.'],
  /* carteles de la pelea */
  ['¡SIN EQUILIBRIO!', 'BROKEN BALANCE!', 'SEM EQUILÍBRIO!'],
  ['DERROTADO', 'DEFEATED', 'DERROTADO'],
  ['¡CONTRAGOLPE RELÁMPAGO!', 'LIGHTNING COUNTER!', 'CONTRAGOLPE RELÂMPAGO!'],
  ['¡DESVÍO!', 'PARRY!', 'DESVIO!'],
  ['¡RESURRECCIÓN!', 'RESURRECTION!', 'RESSURREIÇÃO!'],
  /* capítulos y yokai */
  ['La aldea en llamas', 'The Burning Village', 'A aldeia em chamas'],
  ['El templo nevado', 'The Snowy Temple', 'O templo nevado'],
  ['La luna de sangre', 'The Blood Moon', 'A lua de sangue'],
  ['El esqueleto gigante hecho de los que murieron de hambre.', 'The giant skeleton made of those who starved to death.', 'O esqueleto gigante feito dos que morreram de fome.'],
  ['El sapo del pantano que se traga a los viajeros.', 'The swamp toad that swallows travelers whole.', 'O sapo do pântano que engole os viajantes.'],
  ['Batalla de yokai', 'Yokai battle', 'Batalha de yokai'],
  ['Capítulo {0}', 'Chapter {0}', 'Capítulo {0}'],
  ['Etapa {0}/10', 'Stage {0}/10', 'Etapa {0}/10'],
  ['Afilando la hoja…', 'Sharpening the blade…', 'Afiando a lâmina…'],
  /* bendiciones */
  ['Filo afilado', 'Honed Edge', 'Fio afiado'],
  ['Tu espada hace un 20% más de daño.', 'Your sword deals 20% more damage.', 'Sua espada causa 20% mais dano.'],
  ['Piel de hierro', 'Iron Skin', 'Pele de ferro'],
  ['Recibís un 20% menos de daño.', 'You take 20% less damage.', 'Você recebe 20% menos dano.'],
  ['Ojo de halcón', 'Hawk Eye', 'Olho de falcão'],
  ['La ventana para desviar es más amplia.', 'The parry window is wider.', 'A janela para desviar é mais ampla.'],
  ['Sed de sangre', 'Bloodthirst', 'Sede de sangue'],
  ['Curás un 4% del daño que hacés.', 'You heal 4% of the damage you deal.', 'Você cura 4% do dano que causa.'],
  ['Espíritu ardiente', 'Burning Spirit', 'Espírito ardente'],
  ['La habilidad se carga un 50% más rápido.', 'Your skill charges 50% faster.', 'A habilidade carrega 50% mais rápido.'],
  ['Raíz de roble', 'Oak Root', 'Raiz de carvalho'],
  ['Tu equilibrio aguanta un 40% más.', 'Your balance holds 40% longer.', 'Seu equilíbrio aguenta 40% mais.'],
  ['Aliento de dragón', 'Dragon Breath', 'Sopro de dragão'],
  ['Tu vida máxima sube un 20%.', 'Your max health rises by 20%.', 'Sua vida máxima sobe 20%.'],
  ['Pergamino de resurrección', 'Scroll of Resurrection', 'Pergaminho da ressurreição'],
  ['Si caés, te levantás una vez con media vida.', 'If you fall, you rise once with half health.', 'Se cair, você se levanta uma vez com metade da vida.'],
  ['Té verde', 'Green Tea', 'Chá verde'],
  ['Recuperás toda la vida ahora.', 'Restore all your health now.', 'Recupere toda a vida agora.'],
  ['Bolsa de ryo', 'Pouch of Ryo', 'Bolsa de ryo'],
  ['Ganás un 50% más de oro en este capítulo.', 'Earn 50% more gold in this chapter.', 'Ganhe 50% mais ouro neste capítulo.'],
  /* tutorial */
  ['¡Destello blanco! Tocá GUARDIA justo antes del golpe para desviarlo.', 'White flash! Tap GUARD right before the blow to parry it.', 'Clarão branco! Toque GUARDA logo antes do golpe para desviá-lo.'],
  ['¡殺 en rojo! Ese golpe no se bloquea: tocá ATACAR justo antes del impacto.', 'Red 殺! That blow cannot be blocked: tap ATTACK right before it lands.', '殺 vermelho! Esse golpe não se bloqueia: toque ATACAR logo antes do impacto.'],
  ['Acercate con ▶ y tocá ATACAR. Tres toques seguidos hacen un combo.', 'Close in with ▶ and tap ATTACK. Three taps in a row make a combo.', 'Aproxime-se com ▶ e toque ATACAR. Três toques seguidos fazem um combo.'],
  /* menú */
  ['HISTORIA', 'STORY', 'HISTÓRIA'],
  ['BATALLAS DE YOKAI', 'YOKAI BATTLES', 'BATALHAS DE YOKAI'],
  ['HERRERÍA', 'FORGE', 'FERRARIA'],
  ['DOJO', 'DOJO', 'DOJÔ'],
  ['OPCIONES', 'OPTIONS', 'OPÇÕES'],
  ['CÓMO SE JUEGA', 'HOW TO PLAY', 'COMO JOGAR'],
  ['Completado', 'Completed', 'Concluído'],
  ['Mejor: etapa {0}/10', 'Best: stage {0}/10', 'Melhor: etapa {0}/10'],
  ['Terminá el capítulo anterior', 'Finish the previous chapter', 'Termine o capítulo anterior'],
  ['VOLVER', 'BACK', 'VOLTAR'],
  ['Premio: {0} ryo', 'Reward: {0} ryo', 'Prêmio: {0} ryo'],
  ['Se abre al terminar el capítulo {0}', 'Unlocks after chapter {0}', 'Abre ao terminar o capítulo {0}'],
  ['COMPRAR {0}', 'BUY {0}', 'COMPRAR {0}'],
  ['EN LA MANO', 'EQUIPPED', 'EQUIPADA'],
  ['USAR', 'EQUIP', 'USAR'],
  ['MEJORAR {0}', 'UPGRADE {0}', 'MELHORAR {0}'],
  ['nivel {0}', 'level {0}', 'nível {0}'],
  ['Daño {0}', 'Damage {0}', 'Dano {0}'],
  ['Vida', 'Health', 'Vida'],
  ['+30 de vida máxima por nivel.', '+30 max health per level.', '+30 de vida máxima por nível.'],
  ['Filo', 'Edge', 'Fio'],
  ['+7% de daño por nivel.', '+7% damage per level.', '+7% de dano por nível.'],
  ['Equilibrio', 'Balance', 'Equilíbrio'],
  ['+12 de equilibrio por nivel.', '+12 balance per level.', '+12 de equilíbrio por nível.'],
  ['Ki', 'Ki', 'Ki'],
  ['La habilidad carga un 8% más rápido por nivel.', 'Your skill charges 8% faster per level.', 'A habilidade carrega 8% mais rápido por nível.'],
  ['ENTRENAR {0}', 'TRAIN {0}', 'TREINAR {0}'],
  ['AL MÁXIMO', 'MAXED OUT', 'NO MÁXIMO'],
  ['MÚSICA {0}%', 'MUSIC {0}%', 'MÚSICA {0}%'],
  ['EFECTOS {0}%', 'SOUND {0}%', 'EFEITOS {0}%'],
  ['VIBRACIÓN', 'VIBRATION', 'VIBRAÇÃO'],
  ['SACUDIDA DE CÁMARA', 'CAMERA SHAKE', 'TREMOR DE CÂMERA'],
  ['SANGRE', 'BLOOD', 'SANGUE'],
  /* cómo se juega */
  ['para moverte.', 'to move.', 'para se mover.'],
  ['ATACAR', 'ATTACK', 'ATACAR'],
  ['corta; tres toques seguidos hacen un combo.', 'slashes; three taps in a row make a combo.', 'corta; três toques seguidos fazem um combo.'],
  ['Destello blanco', 'White flash', 'Clarão branco'],
  ['tocá GUARDIA justo antes del golpe y lo DESVIÁS: el enemigo pierde equilibrio. Si ya la tenías apretada, sólo bloqueás y perdés equilibrio vos.',
   'tap GUARD right before the blow and you PARRY it: the enemy loses balance. If you were already holding it, you only block and lose balance yourself.',
   'toque GUARDA logo antes do golpe e você o DESVIA: o inimigo perde o equilíbrio. Se já estava segurando, você só bloqueia e perde equilíbrio.'],
  ['un golpe imparable. No se bloquea: esquivalo o tocá ATACAR justo antes del impacto para el CONTRAGOLPE RELÁMPAGO.',
   'an unstoppable blow. It cannot be blocked: dodge it, or tap ATTACK right before it lands for a LIGHTNING COUNTER.',
   'um golpe imparável. Não se bloqueia: esquive ou toque ATACAR logo antes do impacto para o CONTRAGOLPE RELÂMPAGO.'],
  ['la barra amarilla. Si se vacía, quedás aturdido. Al enemigo le pasa lo mismo, y aturdido recibe casi el doble.',
   'the yellow bar. If it runs out, you are stunned. The same goes for the enemy, and a stunned enemy takes almost double damage.',
   'a barra amarela. Se esvaziar, você fica atordoado. O mesmo vale para o inimigo, e atordoado ele recebe quase o dobro.'],
  ['HABILIDAD', 'SKILL', 'HABILIDADE'],
  ['se carga golpeando y desviando. Cada espada trae la suya.', 'charges as you hit and parry. Each sword has its own.', 'carrega golpeando e desviando. Cada espada tem a sua.'],
  /* pausa, cartas y resultados */
  ['PAUSA', 'PAUSED', 'PAUSA'],
  ['SEGUIR', 'RESUME', 'CONTINUAR'],
  ['ABANDONAR', 'QUIT', 'ABANDONAR'],
  ['Etapa {0} superada', 'Stage {0} cleared', 'Etapa {0} superada'],
  ['Elegí una bendición', 'Choose a blessing', 'Escolha uma bênção'],
  ['¡CAPÍTULO COMPLETADO!', 'CHAPTER COMPLETE!', 'CAPÍTULO CONCLUÍDO!'],
  ['¡YOKAI DERROTADO!', 'YOKAI DEFEATED!', 'YOKAI DERROTADO!'],
  ['Oro ganado', 'Gold earned', 'Ouro ganho'],
  ['Desvíos', 'Parries', 'Desvios'],
  ['Contragolpes', 'Counters', 'Contragolpes'],
  ['Golpes', 'Hits', 'Golpes'],
  ['CONTINUAR', 'CONTINUE', 'CONTINUAR'],
  ['HAS CAÍDO', 'YOU HAVE FALLEN', 'VOCÊ CAIU'],
  ['Llegaste a la etapa {0}/10.', 'You reached stage {0}/10.', 'Você chegou à etapa {0}/10.'],
  ['El oro ganado queda: {0} ryo.', 'You keep the gold you earned: {0} ryo.', 'O ouro ganho fica: {0} ryo.'],
  ['Cuando brille en blanco, apretá GUARDIA justo antes: no la dejes apretada.', 'When it flashes white, press GUARD right before: do not hold it down.', 'Quando brilhar em branco, aperte GUARDA logo antes: não a deixe apertada.'],
  ['El 殺 rojo no se bloquea: esquivá o atacá justo antes del golpe.', 'The red 殺 cannot be blocked: dodge or attack right before the blow.', 'O 殺 vermelho não se bloqueia: esquive ou ataque logo antes do golpe.'],
  ['Si te quedás sin equilibrio, alejate y dejalo volver.', 'If you run out of balance, back off and let it recover.', 'Se ficar sem equilíbrio, afaste-se e deixe-o voltar.'],
  ['En la herrería y el dojo el oro se vuelve fuerza.', 'At the forge and the dojo, gold becomes strength.', 'Na ferraria e no dojô, o ouro vira força.'],
  ['REINTENTAR', 'RETRY', 'TENTAR DE NOVO'],
  ['MENÚ', 'MENU', 'MENU'],
];
