const {chromium}=require('/tmp/ui/node_modules/playwright');
const O=process.env.SALIDA||'/tmp/ui/mate/';
(async()=>{const b=await chromium.launch({executablePath:'/opt/pw-browsers/chromium-1194/chrome-linux/chrome',args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-webgl','--ignore-gpu-blocklist']});
 const p=await b.newPage({viewport:{width:412,height:892},hasTouch:true,isMobile:true,deviceScaleFactor:2.625,locale:'es-AR'});
 const errs=[]; p.on('pageerror',e=>errs.push('PAGE '+e.message+' '+(e.stack||'').split('\n')[1])); p.on('console',m=>{ if(m.type()==='error') errs.push('CON '+m.text().slice(0,200)); });
 const cdp=await p.context().newCDPSession(p);
 await p.goto('file:///tmp/ui/mate_b.html'); await p.waitForTimeout(1500);
 const m=await p.evaluate(()=>__M.medida());
 const pg=(x,y)=>{ const sx=x*m.SW/m.W, sy=y*m.SH/m.H; return m.GIRADO?{x:412-sy,y:sx}:{x:sx,y:sy}; };
 const act={}; const send=t=>cdp.send('Input.dispatchTouchEvent',{type:t,touchPoints:Object.entries(act).map(([id,q])=>({...pg(q[0],q[1]),id:+id}))});
 const pon=async(id,x,y)=>{ act[id]=[x,y]; await send('touchStart'); }, mueve=async(id,x,y)=>{ act[id]=[x,y]; await send('touchMove'); }, saca=async id=>{ delete act[id]; await send('touchEnd'); };
 const st=()=>p.evaluate(()=>{ const H=__M.HE; return {plan:!!__M.J.planeo,x:+H.x.toFixed(2),y:+H.y.toFixed(2),vx:+H.vx.toFixed(1),vy:+H.vy.toFixed(1),est:H.est,ts:+__M.J.ts.toFixed(2),pts:__M.J.puntos,apunta:__M.CTRL.apunta,blanco:__M.CTRL.blanco&&__M.CTRL.blanco.cosa.tipo,tiros:__M.J.tiros,vivos:__M.ENEM.filter(e=>!e.muerto).length}; });
 await p.evaluate(()=>{ __M.jugar(0,false); __M.saltarCine(); }); await p.waitForTimeout(800);
 const W=m.W, H=m.H, cI={x:41,y:H-37}, cD={x:W-41,y:H-37};
 console.log('0', JSON.stringify(await st()));
 await pon(1, cI.x+3, cI.y); await mueve(1, cI.x+12, cI.y-10); await mueve(1, cI.x+14, cI.y-14); await p.waitForTimeout(500); await p.screenshot({path:O+'k1.png'}); console.log('planea', JSON.stringify(await st()));
 await saca(1); await p.waitForTimeout(120); console.log('salta', JSON.stringify(await st())); await p.waitForTimeout(1500); console.log('cae', JSON.stringify(await st()));
 await pon(1, cI.x, cI.y); await mueve(1, cI.x+20, cI.y); await mueve(1, cI.x+25, cI.y+1); await p.waitForTimeout(300); await saca(1); await p.waitForTimeout(150); console.log('desliza', JSON.stringify(await st())); await p.waitForTimeout(1200);
 await p.evaluate(()=>{ __M.HE.x=25.5; __M.HE.y=6; __M.HE.est='suelo'; }); await p.waitForTimeout(700);
 await pon(2, cD.x, cD.y); await mueve(2, cD.x+10, cD.y+1); await mueve(2, cD.x+18, cD.y+2); await p.waitForTimeout(200); await p.screenshot({path:O+'k2.png'}); await p.waitForTimeout(1000); console.log('apunta', JSON.stringify(await st()));
 await saca(2); await p.waitForTimeout(300);
 await pon(3, W/2, H/2); await p.waitForTimeout(80); await saca(3); await p.waitForTimeout(200); console.log('toque', JSON.stringify(await st()));
 console.log(errs.slice(0,8)); await b.close(); })();
